Changes create company
thony-vieira/tropicalrb pull request #38
Opened 2024-03-22 14:24 UTC by thony-vieira

2024-03-25 18:56 UTC, felipeabdo commented
Aprovado

2024-03-25 18:57 UTC, felipeabdo approved these changes
Aprovado

2024-03-26 20:24 UTC, RonMon80 requested changes
dei uma olhada aqui na PR com o Juca e ele sugeriu essas mudanças. Vejam se faz sentido.

2024-03-26 20:24 UTC, RonMon80 commented on app/models/company.rb
> +
@thony-vieira ao invés de usarmos 'setores' em portugues, seria melhor matermos tudo em ingles.

2024-03-26 20:24 UTC, RonMon80 commented on app/views/companies/_form.html.erb
> +      <%= f.input :segment, collection: Company::SETORES %>
@thony-vieira mesma questão do portugues ingles aqui.

2024-03-26 20:24 UTC, RonMon80 commented on db/migrate/20240220134631_add_status_to_companies.rb
> +    add_column :companies, :status, :string, default: "Ativo"
@thony-vieira se quiser manter a alteração na migração todo mundo terá que fazer o drop no banco de dados para reflitir para todos. O ideal seria fazer uma nova migração apenas alterando o default da coluna status.

2024-03-26 21:14 UTC, thony-vieira reviewed
Revisado, e realizado alterações conforme sugerido. Criei uma nova migração para evitar problemas.

2024-03-26 21:26 UTC, RonMon80 requested changes
confere o default pq a migração foi gerada, porem não está fazendo nada.

2024-03-26 21:26 UTC, RonMon80 commented on db/migrate/20240326210959_change_default_status_to_ativo_in_companies.rb
> +  def change
a migração nào esta alterando o default. Confere o arquivo shema para ver se o default do campo status esta como ativo.
![image](https://github.com/thony-vieira/tropicalrb/assets/116599853/994ebe88-8a8e-4f38-abbd-beb786d1a186)

2024-03-26 21:38 UTC, thony-vieira commented on db/migrate/20240326210959_change_default_status_to_ativo_in_companies.rb
> +  def change
resolvido.

2024-03-26 22:12 UTC, RonMon80 approved these changes

2024-03-26 22:12 UTC, merged